config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"
  resources :teachers, only: [:index, :show] do
    resources :reviews, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :teacher
  validates :content, length: { minimum: 20 }
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @teacher = Teacher.find(params[:teacher_id])
    @review = Review.new(review_params)
    @review.teacher = @teacher

    respond_to do |format|
      if @review.save
        format.html { redirect_to teacher_path(@teacher) }
        format.json # Follow the classic Rails flow and look for a create.json view
      else
        format.html { render "teachers/show", status: :unprocessable_entity }
        format.json # Follow the classic Rails flow and look for a create.json view
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.find(params[:id])
    @review = Review.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeachersAjaxBatch989Test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_form.html.erb
<%= simple_form_for([ teacher, review ],
                    data: {
                      insert_in_list_target: "form",
                      action: "submit->insert-in-list#send"
                    }) do |f| %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit %>
<% end %>

app/views/teachers/_review.html.erb
<p><%= review.content %></p>

app/views/teachers/index.html.erb
<h1>Teachers</h1>

<ul>
  <% @teachers.each do |teacher| %>
    <li><%= link_to teacher.name, teacher %></li>
  <% end %>
</ul>

app/views/teachers/show.html.erb
<h1><%= @teacher.name %> <small><%= @teacher.campus %></small></h1>
<h2>
  <%= pluralize @teacher.reviews.size, "review" %>
</h2>

<div data-controller="insert-in-list" data-insert-in-list-position-value="beforeend">
  <div id="reviews" data-insert-in-list-target="items">
    <% if @teacher.reviews.blank? %>
      Be the first to leave a review for <%= @teacher.name %>
    <% else %>
      <%= render partial: "teachers/review", collection: @teacher.reviews, as: :review %>
    <% end %>
  </div>

  <%= simple_form_for([ @teacher, @review ],
    data: {insert_in_list_target: "form",
    action: "submit->insert-in-list#send"}) do |f| %>
    <%= f.input :content, as: :text %>
    <%= f.button :submit, class: 'btn btn-dark' %>
  <% end %>
</div>

<%= link_to "< Back to Home",  teachers_path %>